//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SnapDoc.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SnapDoc.Resources.Languages.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Abbrechen ähnelt.
        /// </summary>
        internal static string abbrechen {
            get {
                return ResourceManager.GetString("abbrechen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Adresse ähnelt.
        /// </summary>
        internal static string adresse {
            get {
                return ResourceManager.GetString("adresse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die alle Icons ähnelt.
        /// </summary>
        internal static string alle_icons {
            get {
                return ResourceManager.GetString("alle_icons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anker X ähnelt.
        /// </summary>
        internal static string anker_x {
            get {
                return ResourceManager.GetString("anker_x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anker Y ähnelt.
        /// </summary>
        internal static string anker_y {
            get {
                return ResourceManager.GetString("anker_y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die App-Modus ähnelt.
        /// </summary>
        internal static string app_modus {
            get {
                return ResourceManager.GetString("app_modus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die App-Settings ähnelt.
        /// </summary>
        internal static string app_settings {
            get {
                return ResourceManager.GetString("app_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die auf einen anderen Plan kopieren/verschieben ähnelt.
        /// </summary>
        internal static string auf_einen_anderen_plan_kopieren_verschieben {
            get {
                return ResourceManager.GetString("auf_einen_anderen_plan_kopieren_verschieben", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auflösung PDF-Umwandlung ähnelt.
        /// </summary>
        internal static string aufloesung_pdf_umwandlung {
            get {
                return ResourceManager.GetString("aufloesung_pdf_umwandlung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ausgeblendete Pläne ähnelt.
        /// </summary>
        internal static string ausgeblendete_plaene {
            get {
                return ResourceManager.GetString("ausgeblendete_plaene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auto-Skalierung sperren ähnelt.
        /// </summary>
        internal static string auto_skalierung_sperren {
            get {
                return ResourceManager.GetString("auto_skalierung_sperren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ◀ Automatische Drehung ähnelt.
        /// </summary>
        internal static string automatische_drehung {
            get {
                return ResourceManager.GetString("automatische_drehung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ◀ Automatische Grössenanpassung ähnelt.
        /// </summary>
        internal static string automatische_groessenanpassung {
            get {
                return ResourceManager.GetString("automatische_groessenanpassung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Automatische Schriftgrösse ähnelt.
        /// </summary>
        internal static string automatische_schriftgroesse {
            get {
                return ResourceManager.GetString("automatische_schriftgroesse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bearbeiten ähnelt.
        /// </summary>
        internal static string bearbeiten {
            get {
                return ResourceManager.GetString("bearbeiten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Berechtigung fehlt ähnelt.
        /// </summary>
        internal static string berechtigung_fehlt {
            get {
                return ResourceManager.GetString("berechtigung_fehlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Diese Funktion benötigt Zugriff auf Kamera und Dateien. Bitte aktiviere die Berechtigung in den Einstellungen deines Geräts. ähnelt.
        /// </summary>
        internal static string berechtigung_kamera_dateien_info {
            get {
                return ResourceManager.GetString("berechtigung_kamera_dateien_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bericht exportieren ähnelt.
        /// </summary>
        internal static string bericht_exportieren {
            get {
                return ResourceManager.GetString("bericht_exportieren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bericht wird gespeichert... ähnelt.
        /// </summary>
        internal static string bericht_wird_gespeichert {
            get {
                return ResourceManager.GetString("bericht_wird_gespeichert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bericht wird geteilt... ähnelt.
        /// </summary>
        internal static string bericht_wird_geteilt {
            get {
                return ResourceManager.GetString("bericht_wird_geteilt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bericht wurde gespeichert. ähnelt.
        /// </summary>
        internal static string bericht_wurde_gespeichert {
            get {
                return ResourceManager.GetString("bericht_wurde_gespeichert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bericht wurde geteilt. ähnelt.
        /// </summary>
        internal static string bericht_wurde_geteilt {
            get {
                return ResourceManager.GetString("bericht_wurde_geteilt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bericht wurde nicht gespeichert. ähnelt.
        /// </summary>
        internal static string bericht_wurde_nicht_gespeichert {
            get {
                return ResourceManager.GetString("bericht_wurde_nicht_gespeichert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bericht wurde nicht geteilt. ähnelt.
        /// </summary>
        internal static string bericht_wurde_nicht_geteilt {
            get {
                return ResourceManager.GetString("bericht_wurde_nicht_geteilt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beschreibung ähnelt.
        /// </summary>
        internal static string beschreibung {
            get {
                return ResourceManager.GetString("beschreibung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bezeichnung ähnelt.
        /// </summary>
        internal static string bezeichnung {
            get {
                return ResourceManager.GetString("bezeichnung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bildkomprimierung ähnelt.
        /// </summary>
        internal static string bildkomprimierung {
            get {
                return ResourceManager.GetString("bildkomprimierung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte wähle ein Bild aus... ähnelt.
        /// </summary>
        internal static string bitte_waehle_bild {
            get {
                return ResourceManager.GetString("bitte_waehle_bild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte wähle eine Zip-Datei aus ähnelt.
        /// </summary>
        internal static string bitte_waehle_zip {
            get {
                return ResourceManager.GetString("bitte_waehle_zip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Blau (B) ähnelt.
        /// </summary>
        internal static string blau_b {
            get {
                return ResourceManager.GetString("blau_b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Datei konnte nicht importiert werden. ähnelt.
        /// </summary>
        internal static string datei_konnte_nicht_importiert_werden {
            get {
                return ResourceManager.GetString("datei_konnte_nicht_importiert_werden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Daten werden komprimiert... ähnelt.
        /// </summary>
        internal static string daten_werden_komprimiert {
            get {
                return ResourceManager.GetString("daten_werden_komprimiert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datum ähnelt.
        /// </summary>
        internal static string datum {
            get {
                return ResourceManager.GetString("datum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deckkraft ähnelt.
        /// </summary>
        internal static string deckkraft {
            get {
                return ResourceManager.GetString("deckkraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Sprache wird erst nach einem Neustart gewechselt. ähnelt.
        /// </summary>
        internal static string die_sprache_wird_erst_nach_einem_neustart_gewechselt {
            get {
                return ResourceManager.GetString("die_sprache_wird_erst_nach_einem_neustart_gewechselt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Distanz messen ähnelt.
        /// </summary>
        internal static string distanz_messen {
            get {
                return ResourceManager.GetString("distanz_messen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Doppelklick, um Farbe zu löschen ähnelt.
        /// </summary>
        internal static string doppelklick_farbe_loeschen {
            get {
                return ResourceManager.GetString("doppelklick_farbe_loeschen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Doppelklick, um Icon zu bearbeiten ähnelt.
        /// </summary>
        internal static string doppelklick_icon_bearbeiten {
            get {
                return ResourceManager.GetString("doppelklick_icon_bearbeiten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ◀ Drehung fixiert ähnelt.
        /// </summary>
        internal static string drehung_fixiert {
            get {
                return ResourceManager.GetString("drehung_fixiert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dunkel ähnelt.
        /// </summary>
        internal static string dunkel {
            get {
                return ResourceManager.GetString("dunkel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Eigene Icons ähnelt.
        /// </summary>
        internal static string eigene_icons {
            get {
                return ResourceManager.GetString("eigene_icons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Einstellungen öffnen ähnelt.
        /// </summary>
        internal static string einstellungen_oeffnen {
            get {
                return ResourceManager.GetString("einstellungen_oeffnen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Empfehlung ähnelt.
        /// </summary>
        internal static string empfehlung {
            get {
                return ResourceManager.GetString("empfehlung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Erstellen ähnelt.
        /// </summary>
        internal static string erstellen {
            get {
                return ResourceManager.GetString("erstellen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Erweiterte Einstellungen ähnelt.
        /// </summary>
        internal static string erweiterte_einstellungen {
            get {
                return ResourceManager.GetString("erweiterte_einstellungen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export-Vorlage ähnelt.
        /// </summary>
        internal static string export_vorlage {
            get {
                return ResourceManager.GetString("export_vorlage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exportiere Foto-Overlays ähnelt.
        /// </summary>
        internal static string exportiere_foto_overlays {
            get {
                return ResourceManager.GetString("exportiere_foto_overlays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exportiere Fotos ähnelt.
        /// </summary>
        internal static string exportiere_fotos {
            get {
                return ResourceManager.GetString("exportiere_fotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exportiere Pin-Icons ähnelt.
        /// </summary>
        internal static string exportiere_pin_icons {
            get {
                return ResourceManager.GetString("exportiere_pin_icons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exportiere Pläne ähnelt.
        /// </summary>
        internal static string exportiere_plaene {
            get {
                return ResourceManager.GetString("exportiere_plaene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exportiere Positionsbilder ähnelt.
        /// </summary>
        internal static string exportiere_positionsbilder {
            get {
                return ResourceManager.GetString("exportiere_positionsbilder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wählen Sie eine Exportvorlage oder importieren Sie eine neue. ähnelt.
        /// </summary>
        internal static string exportvorlage_waehlen_oder_importieren {
            get {
                return ResourceManager.GetString("exportvorlage_waehlen_oder_importieren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Farb-Thema ähnelt.
        /// </summary>
        internal static string farb_thema {
            get {
                return ResourceManager.GetString("farb_thema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ▼      Farbdefinition      ▼ ähnelt.
        /// </summary>
        internal static string farbdefinition {
            get {
                return ResourceManager.GetString("farbdefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Farbe und Stiftbreite wählen ähnelt.
        /// </summary>
        internal static string farbe_und_stiftbreite_waehlen {
            get {
                return ResourceManager.GetString("farbe_und_stiftbreite_waehlen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Farbe wählen ähnelt.
        /// </summary>
        internal static string farbe_waehlen {
            get {
                return ResourceManager.GetString("farbe_waehlen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Farben entfernen ähnelt.
        /// </summary>
        internal static string farben_entfernen {
            get {
                return ResourceManager.GetString("farben_entfernen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Farben hinzufügen ähnelt.
        /// </summary>
        internal static string farben_hinzufuegen {
            get {
                return ResourceManager.GetString("farben_hinzufuegen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Farbschema ähnelt.
        /// </summary>
        internal static string farbschema {
            get {
                return ResourceManager.GetString("farbschema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Farbwert (H) ähnelt.
        /// </summary>
        internal static string farbwert_h {
            get {
                return ResourceManager.GetString("farbwert_h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler ähnelt.
        /// </summary>
        internal static string fehler {
            get {
                return ResourceManager.GetString("fehler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler beim Starten ähnelt.
        /// </summary>
        internal static string fehler_beim_starten {
            get {
                return ResourceManager.GetString("fehler_beim_starten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler beim Stoppen ähnelt.
        /// </summary>
        internal static string fehler_beim_stoppen {
            get {
                return ResourceManager.GetString("fehler_beim_stoppen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler beim Importieren des Bildes ähnelt.
        /// </summary>
        internal static string fehler_bild_import {
            get {
                return ResourceManager.GetString("fehler_bild_import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler bei Standortabfrage ähnelt.
        /// </summary>
        internal static string fehler_standortabfrage {
            get {
                return ResourceManager.GetString("fehler_standortabfrage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fläche messen ähnelt.
        /// </summary>
        internal static string flaeche_messen {
            get {
                return ResourceManager.GetString("flaeche_messen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Formatieren ähnelt.
        /// </summary>
        internal static string formatieren {
            get {
                return ResourceManager.GetString("formatieren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Formen zeichnen ähnelt.
        /// </summary>
        internal static string formen_zeichnen {
            get {
                return ResourceManager.GetString("formen_zeichnen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Foto auf Fenstergrösse zoomen ähnelt.
        /// </summary>
        internal static string foto_auf_fenstergroesse_zoomen {
            get {
                return ResourceManager.GetString("foto_auf_fenstergroesse_zoomen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Foto aufnehmen ähnelt.
        /// </summary>
        internal static string foto_aufnehmen {
            get {
                return ResourceManager.GetString("foto_aufnehmen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Foto (Breite) ähnelt.
        /// </summary>
        internal static string foto_breite {
            get {
                return ResourceManager.GetString("foto_breite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Foto Galerie ähnelt.
        /// </summary>
        internal static string foto_galerie {
            get {
                return ResourceManager.GetString("foto_galerie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Foto löschen ähnelt.
        /// </summary>
        internal static string foto_loeschen {
            get {
                return ResourceManager.GetString("foto_loeschen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fotos ähnelt.
        /// </summary>
        internal static string fotos {
            get {
                return ResourceManager.GetString("fotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Freihandlinie zeichnen ähnelt.
        /// </summary>
        internal static string freihandlinie_zeichnen {
            get {
                return ResourceManager.GetString("freihandlinie_zeichnen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Füllfarbe ähnelt.
        /// </summary>
        internal static string fuellfarbe {
            get {
                return ResourceManager.GetString("fuellfarbe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die GPS aktiv ähnelt.
        /// </summary>
        internal static string gps_aktiv {
            get {
                return ResourceManager.GetString("gps_aktiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die GPS ist deaktiviert ähnelt.
        /// </summary>
        internal static string gps_deaktiviert {
            get {
                return ResourceManager.GetString("gps_deaktiviert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die GPS gestoppt ähnelt.
        /// </summary>
        internal static string gps_gestoppt {
            get {
                return ResourceManager.GetString("gps_gestoppt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die GPS konnte nicht gestartet werden ähnelt.
        /// </summary>
        internal static string gps_start_fehler {
            get {
                return ResourceManager.GetString("gps_start_fehler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Um die Standorterkennung zu aktivieren, bitte GPS in den Systemeinstellungen einschalten. ähnelt.
        /// </summary>
        internal static string gps_system_einschalten_aufforderung {
            get {
                return ResourceManager.GetString("gps_system_einschalten_aufforderung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ◀ Grösse fixiert ähnelt.
        /// </summary>
        internal static string groesse_fixiert {
            get {
                return ResourceManager.GetString("groesse_fixiert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Grösse Pinbeschriftung ähnelt.
        /// </summary>
        internal static string groesse_pinbeschriftung {
            get {
                return ResourceManager.GetString("groesse_pinbeschriftung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Grün (G) ähnelt.
        /// </summary>
        internal static string gruen_g {
            get {
                return ResourceManager.GetString("gruen_g", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hell ähnelt.
        /// </summary>
        internal static string hell {
            get {
                return ResourceManager.GetString("hell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Helligkeit (L) ähnelt.
        /// </summary>
        internal static string helligkeit_l {
            get {
                return ResourceManager.GetString("helligkeit_l", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hinweis ähnelt.
        /// </summary>
        internal static string hinweis {
            get {
                return ResourceManager.GetString("hinweis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Icon auswählen ähnelt.
        /// </summary>
        internal static string icon_auswählen {
            get {
                return ResourceManager.GetString("icon_auswählen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Icon löschen ähnelt.
        /// </summary>
        internal static string icon_loeschen {
            get {
                return ResourceManager.GetString("icon_loeschen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Icondefinitionen ähnelt.
        /// </summary>
        internal static string icondefinitionen {
            get {
                return ResourceManager.GetString("icondefinitionen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Icondefinitionen zurücksetzen ähnelt.
        /// </summary>
        internal static string icondefinitionen_zuruecksetzen {
            get {
                return ResourceManager.GetString("icondefinitionen_zuruecksetzen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die inaktive Fotos ausblenden ähnelt.
        /// </summary>
        internal static string inaktive_fotos_ausblenden {
            get {
                return ResourceManager.GetString("inaktive_fotos_ausblenden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Inaktive Pläne ausblenden ähnelt.
        /// </summary>
        internal static string inaktive_plaene_ausblenden {
            get {
                return ResourceManager.GetString("inaktive_plaene_ausblenden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kartenservice ähnelt.
        /// </summary>
        internal static string kartenservice {
            get {
                return ResourceManager.GetString("kartenservice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kategorie ähnelt.
        /// </summary>
        internal static string kategorie {
            get {
                return ResourceManager.GetString("kategorie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kein Projekt geladen ähnelt.
        /// </summary>
        internal static string kein_projekt_geladen {
            get {
                return ResourceManager.GetString("kein_projekt_geladen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Klicken, um die Vermessung zu starten ähnelt.
        /// </summary>
        internal static string klicken_start_vermessung {
            get {
                return ResourceManager.GetString("klicken_start_vermessung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Klicken, um  ähnelt.
        /// </summary>
        internal static string klicken_um {
            get {
                return ResourceManager.GetString("klicken_um", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die die Linie weiter zu zeichnen ähnelt.
        /// </summary>
        internal static string klicken_weiter_linie {
            get {
                return ResourceManager.GetString("klicken_weiter_linie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die das Polygon weiter zu zeichnen ähnelt.
        /// </summary>
        internal static string klicken_weiter_polygon {
            get {
                return ResourceManager.GetString("klicken_weiter_polygon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die KML-Datei exportieren ähnelt.
        /// </summary>
        internal static string kml_datei_exportieren {
            get {
                return ResourceManager.GetString("kml_datei_exportieren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die KML-Datei wurde gespeichert. ähnelt.
        /// </summary>
        internal static string kml_gespeichert {
            get {
                return ResourceManager.GetString("kml_gespeichert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die KML-Datei wurde nicht gespeichert. ähnelt.
        /// </summary>
        internal static string kml_nicht_gespeichert {
            get {
                return ResourceManager.GetString("kml_nicht_gespeichert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kopie erstellen ähnelt.
        /// </summary>
        internal static string kopie_erstellen {
            get {
                return ResourceManager.GetString("kopie_erstellen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kopieren ähnelt.
        /// </summary>
        internal static string kopieren {
            get {
                return ResourceManager.GetString("kopieren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kritisch ähnelt.
        /// </summary>
        internal static string kritisch {
            get {
                return ResourceManager.GetString("kritisch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kunde/Bauherrschaft ähnelt.
        /// </summary>
        internal static string kunde_bauherrschaft {
            get {
                return ResourceManager.GetString("kunde_bauherrschaft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lade PDF Seiten... ähnelt.
        /// </summary>
        internal static string lade_pdf_seiten {
            get {
                return ResourceManager.GetString("lade_pdf_seiten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Linie ähnelt.
        /// </summary>
        internal static string linie {
            get {
                return ResourceManager.GetString("linie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Linienbreite ähnelt.
        /// </summary>
        internal static string linienbreite {
            get {
                return ResourceManager.GetString("linienbreite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Löschen ähnelt.
        /// </summary>
        internal static string loeschen {
            get {
                return ResourceManager.GetString("loeschen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Max. Pingrösse limitieren ähnelt.
        /// </summary>
        internal static string max_pingroesse_limitieren {
            get {
                return ResourceManager.GetString("max_pingroesse_limitieren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Min. Pingrösse limitieren ähnelt.
        /// </summary>
        internal static string min_pingroesse_limitieren {
            get {
                return ResourceManager.GetString("min_pingroesse_limitieren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Modus für Pinplatzierung ähnelt.
        /// </summary>
        internal static string modus_fuer_pinplatzierung {
            get {
                return ResourceManager.GetString("modus_fuer_pinplatzierung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die nach aktiv/inaktiv ähnelt.
        /// </summary>
        internal static string nach_aktiv_inaktiv {
            get {
                return ResourceManager.GetString("nach_aktiv_inaktiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die nach Aufnahmedatum ähnelt.
        /// </summary>
        internal static string nach_aufnahmedatum {
            get {
                return ResourceManager.GetString("nach_aufnahmedatum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die nach Bezeichnung ähnelt.
        /// </summary>
        internal static string nach_bezeichnung {
            get {
                return ResourceManager.GetString("nach_bezeichnung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die nach Farbe ähnelt.
        /// </summary>
        internal static string nach_farbe {
            get {
                return ResourceManager.GetString("nach_farbe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die nach Name ähnelt.
        /// </summary>
        internal static string nach_name {
            get {
                return ResourceManager.GetString("nach_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die nach Pin ähnelt.
        /// </summary>
        internal static string nach_pin {
            get {
                return ResourceManager.GetString("nach_pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die nach Plan ähnelt.
        /// </summary>
        internal static string nach_plan {
            get {
                return ResourceManager.GetString("nach_plan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die nach Priorität ähnelt.
        /// </summary>
        internal static string nach_prioritaet {
            get {
                return ResourceManager.GetString("nach_prioritaet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die nach Standort ähnelt.
        /// </summary>
        internal static string nach_standort {
            get {
                return ResourceManager.GetString("nach_standort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Neu setzen ähnelt.
        /// </summary>
        internal static string neu_setzen {
            get {
                return ResourceManager.GetString("neu_setzen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die neue Vorlage hochladen ähnelt.
        /// </summary>
        internal static string neue_vorlage_hochladen {
            get {
                return ResourceManager.GetString("neue_vorlage_hochladen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Neues Icon ähnelt.
        /// </summary>
        internal static string neues_icon {
            get {
                return ResourceManager.GetString("neues_icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die neues Icon erstellen ähnelt.
        /// </summary>
        internal static string neues_icon_erstellen {
            get {
                return ResourceManager.GetString("neues_icon_erstellen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Neues Projekt eröffnen... ähnelt.
        /// </summary>
        internal static string neues_projekt_eroeffnen {
            get {
                return ResourceManager.GetString("neues_projekt_eroeffnen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die neues Projekt erstellen ähnelt.
        /// </summary>
        internal static string neues_projekt_erstellen {
            get {
                return ResourceManager.GetString("neues_projekt_erstellen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Objektbezeichnung ähnelt.
        /// </summary>
        internal static string objektbezeichnung {
            get {
                return ResourceManager.GetString("objektbezeichnung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OK ähnelt.
        /// </summary>
        internal static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OpenStreetMap ähnelt.
        /// </summary>
        internal static string osm_karte {
            get {
                return ResourceManager.GetString("osm_karte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Eine oder mehrere PDF-Dateien auswählen ähnelt.
        /// </summary>
        internal static string pdf_dateien_auswaehlen {
            get {
                return ResourceManager.GetString("pdf_dateien_auswaehlen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PDF-Seiten hinzufügen ähnelt.
        /// </summary>
        internal static string pdf_seiten_hinzufügen {
            get {
                return ResourceManager.GetString("pdf_seiten_hinzufügen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PDF wird konvertiert... ähnelt.
        /// </summary>
        internal static string pdf_wird_konvertiert {
            get {
                return ResourceManager.GetString("pdf_wird_konvertiert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pin auf folgenden Plan kopieren ähnelt.
        /// </summary>
        internal static string pin_auf_plan_kopieren {
            get {
                return ResourceManager.GetString("pin_auf_plan_kopieren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pin auf folgenden Plan verschieben ähnelt.
        /// </summary>
        internal static string pin_auf_plan_verschieben {
            get {
                return ResourceManager.GetString("pin_auf_plan_verschieben", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pin auf swisstopo-Karte anzeigen ähnelt.
        /// </summary>
        internal static string pin_auf_swisstopo_karte_anzeigen {
            get {
                return ResourceManager.GetString("pin_auf_swisstopo_karte_anzeigen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pin bearbeiten ähnelt.
        /// </summary>
        internal static string pin_bearbeiten {
            get {
                return ResourceManager.GetString("pin_bearbeiten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pin durch Antippen setzen ähnelt.
        /// </summary>
        internal static string pin_durch_antippen_setzen {
            get {
                return ResourceManager.GetString("pin_durch_antippen_setzen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pin durch Gedrückthalten setzen ähnelt.
        /// </summary>
        internal static string pin_durch_gedrueckthalten_setzen {
            get {
                return ResourceManager.GetString("pin_durch_gedrueckthalten_setzen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pin exportieren ähnelt.
        /// </summary>
        internal static string pin_exportieren {
            get {
                return ResourceManager.GetString("pin_exportieren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pin-Icon (Breite + Höhe) ähnelt.
        /// </summary>
        internal static string pin_icon_breite_hoehe {
            get {
                return ResourceManager.GetString("pin_icon_breite_hoehe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pin in die Bildmitte setzen ähnelt.
        /// </summary>
        internal static string pin_in_die_bildmitte_setzen {
            get {
                return ResourceManager.GetString("pin_in_die_bildmitte_setzen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Für diesen Pin sind noch keine Informationen verfügbar. ähnelt.
        /// </summary>
        internal static string pin_keine_infos {
            get {
                return ResourceManager.GetString("pin_keine_infos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pin Liste ähnelt.
        /// </summary>
        internal static string pin_liste {
            get {
                return ResourceManager.GetString("pin_liste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pin löschen ähnelt.
        /// </summary>
        internal static string pin_loeschen {
            get {
                return ResourceManager.GetString("pin_loeschen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Positionen aller Pins auf der Karte wurden aktualisiert. ähnelt.
        /// </summary>
        internal static string pin_positionen_aktualisiert {
            get {
                return ResourceManager.GetString("pin_positionen_aktualisiert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pin setzen ähnelt.
        /// </summary>
        internal static string pin_setzen {
            get {
                return ResourceManager.GetString("pin_setzen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pinbeschriftung ähnelt.
        /// </summary>
        internal static string pinbeschriftung {
            get {
                return ResourceManager.GetString("pinbeschriftung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pingrösse ähnelt.
        /// </summary>
        internal static string pingroesse {
            get {
                return ResourceManager.GetString("pingroesse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pins ähnelt.
        /// </summary>
        internal static string pins {
            get {
                return ResourceManager.GetString("pins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pläne umsortieren: Gedrückt halten und ziehen ähnelt.
        /// </summary>
        internal static string plaene_umsortieren_gedrueckt_halten_und_ziehen {
            get {
                return ResourceManager.GetString("plaene_umsortieren_gedrueckt_halten_und_ziehen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Plan auf Fenstergrösse zoomen ähnelt.
        /// </summary>
        internal static string plan_auf_fenstergroesse_zoomen {
            get {
                return ResourceManager.GetString("plan_auf_fenstergroesse_zoomen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Plan bearbeiten ähnelt.
        /// </summary>
        internal static string plan_bearbeiten {
            get {
                return ResourceManager.GetString("plan_bearbeiten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Plan-Drehung: ähnelt.
        /// </summary>
        internal static string plan_drehung {
            get {
                return ResourceManager.GetString("plan_drehung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Plan exportieren ähnelt.
        /// </summary>
        internal static string plan_exportieren {
            get {
                return ResourceManager.GetString("plan_exportieren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Plan löschen ähnelt.
        /// </summary>
        internal static string plan_loeschen {
            get {
                return ResourceManager.GetString("plan_loeschen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Planbezeichnung ähnelt.
        /// </summary>
        internal static string planbezeichnung {
            get {
                return ResourceManager.GetString("planbezeichnung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Planfarbe ähnelt.
        /// </summary>
        internal static string planfarbe {
            get {
                return ResourceManager.GetString("planfarbe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Planliste mit Vorschau ähnelt.
        /// </summary>
        internal static string planliste_mit_vorschau {
            get {
                return ResourceManager.GetString("planliste_mit_vorschau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Planrotation sperren ähnelt.
        /// </summary>
        internal static string planrotation_sperren {
            get {
                return ResourceManager.GetString("planrotation_sperren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Polygon ähnelt.
        /// </summary>
        internal static string polygon {
            get {
                return ResourceManager.GetString("polygon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Polylinie zeichnen ähnelt.
        /// </summary>
        internal static string polylinie_zeichnen {
            get {
                return ResourceManager.GetString("polylinie_zeichnen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Position sperren ähnelt.
        /// </summary>
        internal static string position_sperren {
            get {
                return ResourceManager.GetString("position_sperren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Positionsbilder (Breite + Höhe) ähnelt.
        /// </summary>
        internal static string positionsbilder_breite_hoehe {
            get {
                return ResourceManager.GetString("positionsbilder_breite_hoehe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Positionsbilder Zuschnitt ähnelt.
        /// </summary>
        internal static string positionsbilder_zuschnitt {
            get {
                return ResourceManager.GetString("positionsbilder_zuschnitt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Programmeinstellungen zurücksetzen ähnelt.
        /// </summary>
        internal static string programmeinstellungen_zuruecksetzen {
            get {
                return ResourceManager.GetString("programmeinstellungen_zuruecksetzen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Projekt löschen ähnelt.
        /// </summary>
        internal static string projekt_loeschen {
            get {
                return ResourceManager.GetString("projekt_loeschen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Projekt Titel ähnelt.
        /// </summary>
        internal static string projekt_titel {
            get {
                return ResourceManager.GetString("projekt_titel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Projekt wird geladen... ähnelt.
        /// </summary>
        internal static string projekt_wird_geladen {
            get {
                return ResourceManager.GetString("projekt_wird_geladen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Projekt wird importiert... ähnelt.
        /// </summary>
        internal static string projekt_wird_importiert {
            get {
                return ResourceManager.GetString("projekt_wird_importiert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Projektdatei importieren ähnelt.
        /// </summary>
        internal static string projektdatei_importieren {
            get {
                return ResourceManager.GetString("projektdatei_importieren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Projektdaten ähnelt.
        /// </summary>
        internal static string projektdaten {
            get {
                return ResourceManager.GetString("projektdaten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Projekte ähnelt.
        /// </summary>
        internal static string projekte {
            get {
                return ResourceManager.GetString("projekte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Projektleitung ähnelt.
        /// </summary>
        internal static string projektleitung {
            get {
                return ResourceManager.GetString("projektleitung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Projektliste ähnelt.
        /// </summary>
        internal static string projektliste {
            get {
                return ResourceManager.GetString("projektliste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Projektnummer ähnelt.
        /// </summary>
        internal static string projektnummer {
            get {
                return ResourceManager.GetString("projektnummer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Projektverwaltung ähnelt.
        /// </summary>
        internal static string projektverwaltung {
            get {
                return ResourceManager.GetString("projektverwaltung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Projektvorgang ähnelt.
        /// </summary>
        internal static string projektvorgang {
            get {
                return ResourceManager.GetString("projektvorgang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Randabstand ähnelt.
        /// </summary>
        internal static string randabstand {
            get {
                return ResourceManager.GetString("randabstand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Raster/Liste umschalten ähnelt.
        /// </summary>
        internal static string raster_liste_umschalten {
            get {
                return ResourceManager.GetString("raster_liste_umschalten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rechteck zeichnen ähnelt.
        /// </summary>
        internal static string rechteck_zeichnen {
            get {
                return ResourceManager.GetString("rechteck_zeichnen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rechtsklick, um Icon zu bearbeiten ähnelt.
        /// </summary>
        internal static string rechtsklick_icon_bearbeiten {
            get {
                return ResourceManager.GetString("rechtsklick_icon_bearbeiten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rechtsklick zum Löschen ähnelt.
        /// </summary>
        internal static string rechtsklick_loeschen {
            get {
                return ResourceManager.GetString("rechtsklick_loeschen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Projekt wird importiert... ähnelt.
        /// </summary>
        internal static string rojekt_wird_importiert {
            get {
                return ResourceManager.GetString("rojekt_wird_importiert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rot (R) ähnelt.
        /// </summary>
        internal static string rot_r {
            get {
                return ResourceManager.GetString("rot_r", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rotation sperren ähnelt.
        /// </summary>
        internal static string rotation_sperren {
            get {
                return ResourceManager.GetString("rotation_sperren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sättigung (S) ähnelt.
        /// </summary>
        internal static string saettigung_s {
            get {
                return ResourceManager.GetString("saettigung_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Schriftgrösse ähnelt.
        /// </summary>
        internal static string schriftgroesse {
            get {
                return ResourceManager.GetString("schriftgroesse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Seiten hinzufügen ähnelt.
        /// </summary>
        internal static string seiten_hinzufuegen {
            get {
                return ResourceManager.GetString("seiten_hinzufuegen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Speichern ähnelt.
        /// </summary>
        internal static string speichern {
            get {
                return ResourceManager.GetString("speichern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sprache ähnelt.
        /// </summary>
        internal static string sprache {
            get {
                return ResourceManager.GetString("sprache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Standard-Icon ähnelt.
        /// </summary>
        internal static string standard_icon {
            get {
                return ResourceManager.GetString("standard_icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Standardeinstellungen laden? ähnelt.
        /// </summary>
        internal static string standardeinstellungen_laden {
            get {
                return ResourceManager.GetString("standardeinstellungen_laden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Standort ähnelt.
        /// </summary>
        internal static string standort {
            get {
                return ResourceManager.GetString("standort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Standortberechtigung wurde nicht erteilt. GPS kann nicht aktiviert werden. ähnelt.
        /// </summary>
        internal static string standort_berechtigung_fehlt {
            get {
                return ResourceManager.GetString("standort_berechtigung_fehlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte aktivieren Sie die Standortdienste im System und in der App, um Positionsdaten nutzen zu können. ähnelt.
        /// </summary>
        internal static string standortdienste_aktivieren_aufforderung {
            get {
                return ResourceManager.GetString("standortdienste_aktivieren_aufforderung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Standortdienste deaktiviert ähnelt.
        /// </summary>
        internal static string standortdienste_deaktiviert {
            get {
                return ResourceManager.GetString("standortdienste_deaktiviert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stiftfarbe ähnelt.
        /// </summary>
        internal static string stiftfarbe {
            get {
                return ResourceManager.GetString("stiftfarbe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Suche... ähnelt.
        /// </summary>
        internal static string suche {
            get {
                return ResourceManager.GetString("suche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die swisstopo Karte ähnelt.
        /// </summary>
        internal static string swisstopo_karte {
            get {
                return ResourceManager.GetString("swisstopo_karte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die swisstopo Karten-Pins ähnelt.
        /// </summary>
        internal static string swisstopo_karten_pins {
            get {
                return ResourceManager.GetString("swisstopo_karten_pins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Text eingeben ähnelt.
        /// </summary>
        internal static string text_eingeben {
            get {
                return ResourceManager.GetString("text_eingeben", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Textfarbe ähnelt.
        /// </summary>
        internal static string textfarbe {
            get {
                return ResourceManager.GetString("textfarbe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Textfeld bearbeiten ähnelt.
        /// </summary>
        internal static string textfeld_bearbeiten {
            get {
                return ResourceManager.GetString("textfeld_bearbeiten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tippen und ziehen, um Distanz zu messen ähnelt.
        /// </summary>
        internal static string tippen_ziehen_messen {
            get {
                return ResourceManager.GetString("tippen_ziehen_messen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (Titel eingeben...) ähnelt.
        /// </summary>
        internal static string titel_eingeben {
            get {
                return ResourceManager.GetString("titel_eingeben", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Titelbild (Höhe) ähnelt.
        /// </summary>
        internal static string titelbild_hoehe {
            get {
                return ResourceManager.GetString("titelbild_hoehe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Titelbild mit der Kamera erstellen ähnelt.
        /// </summary>
        internal static string titelbild_mit_der_kamera_erstellen {
            get {
                return ResourceManager.GetString("titelbild_mit_der_kamera_erstellen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Titelbild von der Festplatte hochladen ähnelt.
        /// </summary>
        internal static string titelbild_von_der_festplatte_hochladen {
            get {
                return ResourceManager.GetString("titelbild_von_der_festplatte_hochladen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Validieren ähnelt.
        /// </summary>
        internal static string validieren {
            get {
                return ResourceManager.GetString("validieren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vermessung ähnelt.
        /// </summary>
        internal static string vermessung {
            get {
                return ResourceManager.GetString("vermessung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verschieben ähnelt.
        /// </summary>
        internal static string verschieben {
            get {
                return ResourceManager.GetString("verschieben", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verzeichnis öffnen ähnelt.
        /// </summary>
        internal static string verzeichnis_oeffnen {
            get {
                return ResourceManager.GetString("verzeichnis_oeffnen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Voreinstellung Skalierung ähnelt.
        /// </summary>
        internal static string voreinstellung_skalierung {
            get {
                return ResourceManager.GetString("voreinstellung_skalierung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vorlage löschen ähnelt.
        /// </summary>
        internal static string vorlage_loeschen {
            get {
                return ResourceManager.GetString("vorlage_loeschen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vorlagen ähnelt.
        /// </summary>
        internal static string vorlagen {
            get {
                return ResourceManager.GetString("vorlagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wähle ein Bild aus ähnelt.
        /// </summary>
        internal static string waehle_bild_aus {
            get {
                return ResourceManager.GetString("waehle_bild_aus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wähle ein Word-Dokument ähnelt.
        /// </summary>
        internal static string waehle_word_dokument {
            get {
                return ResourceManager.GetString("waehle_word_dokument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Warte auf Datei... ähnelt.
        /// </summary>
        internal static string warte_auf_datei {
            get {
                return ResourceManager.GetString("warte_auf_datei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wichtig ähnelt.
        /// </summary>
        internal static string wichtig {
            get {
                return ResourceManager.GetString("wichtig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wollen Sie diese Vorlage wirklich löschen? ähnelt.
        /// </summary>
        internal static string wollen_sie_diese_vorlage_wirklich_loeschen {
            get {
                return ResourceManager.GetString("wollen_sie_diese_vorlage_wirklich_loeschen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wollen Sie diesen Pin wirklich löschen? ähnelt.
        /// </summary>
        internal static string wollen_sie_diesen_pin_wirklich_loeschen {
            get {
                return ResourceManager.GetString("wollen_sie_diesen_pin_wirklich_loeschen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wollen Sie diesen Plan wirklich löschen? ähnelt.
        /// </summary>
        internal static string wollen_sie_diesen_plan_wirklich_loeschen {
            get {
                return ResourceManager.GetString("wollen_sie_diesen_plan_wirklich_loeschen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wollen Sie dieses Bild wirklich löschen? ähnelt.
        /// </summary>
        internal static string wollen_sie_dieses_bild_wirklich_loeschen {
            get {
                return ResourceManager.GetString("wollen_sie_dieses_bild_wirklich_loeschen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wollen Sie dieses Projekt wirklich löschen? ähnelt.
        /// </summary>
        internal static string wollen_sie_dieses_projekt_wirklich_loeschen {
            get {
                return ResourceManager.GetString("wollen_sie_dieses_projekt_wirklich_loeschen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wollen Sie dieses Projekt wirklich als Zip exportieren? ähnelt.
        /// </summary>
        internal static string wollen_sie_projekt_als_zip_exportieren {
            get {
                return ResourceManager.GetString("wollen_sie_projekt_als_zip_exportieren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zeichnung löschen ähnelt.
        /// </summary>
        internal static string zeichnung_loeschen {
            get {
                return ResourceManager.GetString("zeichnung_loeschen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zeichnung speichern ähnelt.
        /// </summary>
        internal static string zeichnung_speichern {
            get {
                return ResourceManager.GetString("zeichnung_speichern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die zeige Platzhalter-Definitionen ähnelt.
        /// </summary>
        internal static string zeige_platzhalter_definitionen {
            get {
                return ResourceManager.GetString("zeige_platzhalter_definitionen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zeit ähnelt.
        /// </summary>
        internal static string zeit {
            get {
                return ResourceManager.GetString("zeit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ziel auswählen ähnelt.
        /// </summary>
        internal static string ziel_auswaehlen {
            get {
                return ResourceManager.GetString("ziel_auswaehlen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zip Exportieren ähnelt.
        /// </summary>
        internal static string zip_exportieren {
            get {
                return ResourceManager.GetString("zip_exportieren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zip wurde exportiert. ähnelt.
        /// </summary>
        internal static string zip_wurde_exportiert {
            get {
                return ResourceManager.GetString("zip_wurde_exportiert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zu Pin wechseln ähnelt.
        /// </summary>
        internal static string zu_pin_wechseln {
            get {
                return ResourceManager.GetString("zu_pin_wechseln", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zum bearbeiten ziehen ähnelt.
        /// </summary>
        internal static string zum_bearbeiten_ziehen {
            get {
                return ResourceManager.GetString("zum_bearbeiten_ziehen", resourceCulture);
            }
        }
    }
}
