//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SnapDoc.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SnapDoc.Resources.Languages.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die auf einen anderen Plan kopieren/verschieben ähnelt.
        /// </summary>
        internal static string auf_einen_anderen_plan_kopieren_verschieben {
            get {
                return ResourceManager.GetString("auf_einen_anderen_plan_kopieren_verschieben", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bericht exportieren ähnelt.
        /// </summary>
        internal static string bericht_exportieren {
            get {
                return ResourceManager.GetString("bericht_exportieren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beschreibung ähnelt.
        /// </summary>
        internal static string beschreibung {
            get {
                return ResourceManager.GetString("beschreibung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bildkomprimierung ähnelt.
        /// </summary>
        internal static string bildkomprimierung {
            get {
                return ResourceManager.GetString("bildkomprimierung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export-Vorlage ähnelt.
        /// </summary>
        internal static string export_vorlage {
            get {
                return ResourceManager.GetString("export_vorlage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exportiere Foto-Overlays ähnelt.
        /// </summary>
        internal static string exportiere_foto_overlays {
            get {
                return ResourceManager.GetString("exportiere_foto_overlays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exportiere Fotos ähnelt.
        /// </summary>
        internal static string exportiere_fotos {
            get {
                return ResourceManager.GetString("exportiere_fotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exportiere Pin-Icons ähnelt.
        /// </summary>
        internal static string exportiere_pin_icons {
            get {
                return ResourceManager.GetString("exportiere_pin_icons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exportiere Pläne ähnelt.
        /// </summary>
        internal static string exportiere_plaene {
            get {
                return ResourceManager.GetString("exportiere_plaene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exportiere Positionsbilder ähnelt.
        /// </summary>
        internal static string exportiere_positionsbilder {
            get {
                return ResourceManager.GetString("exportiere_positionsbilder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Foto aufnehmen ähnelt.
        /// </summary>
        internal static string foto_aufnehmen {
            get {
                return ResourceManager.GetString("foto_aufnehmen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Foto (Breite) ähnelt.
        /// </summary>
        internal static string foto_breite {
            get {
                return ResourceManager.GetString("foto_breite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Grösse Pinbeschriftung ähnelt.
        /// </summary>
        internal static string groesse_pinbeschriftung {
            get {
                return ResourceManager.GetString("groesse_pinbeschriftung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die neue Vorlage hochladen ähnelt.
        /// </summary>
        internal static string neue_vorlage_hochladen {
            get {
                return ResourceManager.GetString("neue_vorlage_hochladen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pin auf swisstopo-Karte anzeigen ähnelt.
        /// </summary>
        internal static string pin_auf_swisstopo_karte_anzeigen {
            get {
                return ResourceManager.GetString("pin_auf_swisstopo_karte_anzeigen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pin bearbeiten ähnelt.
        /// </summary>
        internal static string pin_bearbeiten {
            get {
                return ResourceManager.GetString("pin_bearbeiten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pin exportieren ähnelt.
        /// </summary>
        internal static string pin_exportieren {
            get {
                return ResourceManager.GetString("pin_exportieren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pin-Icon (Breite + Höhe) ähnelt.
        /// </summary>
        internal static string pin_icon_breite_hoehe {
            get {
                return ResourceManager.GetString("pin_icon_breite_hoehe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pin löschen ähnelt.
        /// </summary>
        internal static string pin_loeschen {
            get {
                return ResourceManager.GetString("pin_loeschen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pinbeschriftung ähnelt.
        /// </summary>
        internal static string pinbeschriftung {
            get {
                return ResourceManager.GetString("pinbeschriftung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Position sperren ähnelt.
        /// </summary>
        internal static string position_sperren {
            get {
                return ResourceManager.GetString("position_sperren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Positionsbilder (Breite + Höhe) ähnelt.
        /// </summary>
        internal static string positionsbilder_breite_hoehe {
            get {
                return ResourceManager.GetString("positionsbilder_breite_hoehe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Positionsbilder Zuschnitt ähnelt.
        /// </summary>
        internal static string positionsbilder_zuschnitt {
            get {
                return ResourceManager.GetString("positionsbilder_zuschnitt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Standort ähnelt.
        /// </summary>
        internal static string standort {
            get {
                return ResourceManager.GetString("standort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (Titel eingeben...) ähnelt.
        /// </summary>
        internal static string titel_eingeben {
            get {
                return ResourceManager.GetString("titel_eingeben", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Titelbild (Höhe) ähnelt.
        /// </summary>
        internal static string titelbild_hoehe {
            get {
                return ResourceManager.GetString("titelbild_hoehe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vorlage löschen ähnelt.
        /// </summary>
        internal static string vorlage_loeschen {
            get {
                return ResourceManager.GetString("vorlage_loeschen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die zeige Platzhalter-Definitionen ähnelt.
        /// </summary>
        internal static string zeige_platzhalter_definitionen {
            get {
                return ResourceManager.GetString("zeige_platzhalter_definitionen", resourceCulture);
            }
        }
    }
}
