//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SnapDoc.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources_en() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SnapDoc.Resources.Languages.AppResources_en", typeof(AppResources_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anchor X ähnelt.
        /// </summary>
        internal static string anker_x {
            get {
                return ResourceManager.GetString("anker_x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anchor Y ähnelt.
        /// </summary>
        internal static string anker_y {
            get {
                return ResourceManager.GetString("anker_y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copy/move to another plan ähnelt.
        /// </summary>
        internal static string auf_einen_anderen_plan_kopieren_verschieben {
            get {
                return ResourceManager.GetString("auf_einen_anderen_plan_kopieren_verschieben", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lock auto-scaling ähnelt.
        /// </summary>
        internal static string auto_skalierung_sperren {
            get {
                return ResourceManager.GetString("auto_skalierung_sperren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ◀ Automatic rotation ähnelt.
        /// </summary>
        internal static string automatische_drehung {
            get {
                return ResourceManager.GetString("automatische_drehung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ◀ Automatic size adjustment ähnelt.
        /// </summary>
        internal static string automatische_groessenanpassung {
            get {
                return ResourceManager.GetString("automatische_groessenanpassung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export report ähnelt.
        /// </summary>
        internal static string bericht_exportieren {
            get {
                return ResourceManager.GetString("bericht_exportieren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Description ähnelt.
        /// </summary>
        internal static string beschreibung {
            get {
                return ResourceManager.GetString("beschreibung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Label ähnelt.
        /// </summary>
        internal static string bezeichnung {
            get {
                return ResourceManager.GetString("bezeichnung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Image compression: ähnelt.
        /// </summary>
        internal static string bildkomprimierung {
            get {
                return ResourceManager.GetString("bildkomprimierung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Date ähnelt.
        /// </summary>
        internal static string datum {
            get {
                return ResourceManager.GetString("datum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Opacity: ähnelt.
        /// </summary>
        internal static string deckkraft {
            get {
                return ResourceManager.GetString("deckkraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ◀ Rotation fixed ähnelt.
        /// </summary>
        internal static string drehung_fixiert {
            get {
                return ResourceManager.GetString("drehung_fixiert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export template ähnelt.
        /// </summary>
        internal static string export_vorlage {
            get {
                return ResourceManager.GetString("export_vorlage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export photo overlays ähnelt.
        /// </summary>
        internal static string exportiere_foto_overlays {
            get {
                return ResourceManager.GetString("exportiere_foto_overlays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export photos ähnelt.
        /// </summary>
        internal static string exportiere_fotos {
            get {
                return ResourceManager.GetString("exportiere_fotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export pin icons ähnelt.
        /// </summary>
        internal static string exportiere_pin_icons {
            get {
                return ResourceManager.GetString("exportiere_pin_icons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export plans ähnelt.
        /// </summary>
        internal static string exportiere_plaene {
            get {
                return ResourceManager.GetString("exportiere_plaene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export position images ähnelt.
        /// </summary>
        internal static string exportiere_positionsbilder {
            get {
                return ResourceManager.GetString("exportiere_positionsbilder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Choose color and pen width ähnelt.
        /// </summary>
        internal static string farbe_und_stiftbreite_waehlen {
            get {
                return ResourceManager.GetString("farbe_und_stiftbreite_waehlen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Choose color ähnelt.
        /// </summary>
        internal static string farbe_waehlen {
            get {
                return ResourceManager.GetString("farbe_waehlen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Draw shapes ähnelt.
        /// </summary>
        internal static string formen_zeichnen {
            get {
                return ResourceManager.GetString("formen_zeichnen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zoom photo to window size ähnelt.
        /// </summary>
        internal static string foto_auf_fenstergroesse_zoomen {
            get {
                return ResourceManager.GetString("foto_auf_fenstergroesse_zoomen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Take photo ähnelt.
        /// </summary>
        internal static string foto_aufnehmen {
            get {
                return ResourceManager.GetString("foto_aufnehmen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ◀ Size fixed ähnelt.
        /// </summary>
        internal static string groesse_fixiert {
            get {
                return ResourceManager.GetString("groesse_fixiert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete icon ähnelt.
        /// </summary>
        internal static string icon_loeschen {
            get {
                return ResourceManager.GetString("icon_loeschen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Category ähnelt.
        /// </summary>
        internal static string kategorie {
            get {
                return ResourceManager.GetString("kategorie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Brush size: ähnelt.
        /// </summary>
        internal static string pinselgroesse {
            get {
                return ResourceManager.GetString("pinselgroesse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lock rotation ähnelt.
        /// </summary>
        internal static string rotation_sperren {
            get {
                return ResourceManager.GetString("rotation_sperren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Default icon ähnelt.
        /// </summary>
        internal static string standard_icon {
            get {
                return ResourceManager.GetString("standard_icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Default scaling: ähnelt.
        /// </summary>
        internal static string voreinstellung_skalierung {
            get {
                return ResourceManager.GetString("voreinstellung_skalierung", resourceCulture);
            }
        }
    }
}
