<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>net10.0-android;net10.0-ios</TargetFrameworks>
		<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net10.0-windows10.0.26100.0</TargetFrameworks>
		<ApplicationTitle>SnapDoc</ApplicationTitle>
		<ApplicationId>com.ebbe.snapdoc</ApplicationId>
		<ApplicationDisplayVersion>2.5.0</ApplicationDisplayVersion>
		<Version>2.5.0</Version>
		<ApplicationVersion>78</ApplicationVersion>
		<UseMaui>true</UseMaui>
		<MauiEnableTizenTargeting>false</MauiEnableTizenTargeting>
		<SingleProject>true</SingleProject>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<Authors>Michael Fankhauser</Authors>
		<Company>Emch+Berger Bern AG</Company>
		<RootNamespace>SnapDoc</RootNamespace>
		<DefaultLanguage>de-DE</DefaultLanguage>
		<OutputType>Exe</OutputType>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<MauiEnableXamlCBindingWithSourceCompilation>true</MauiEnableXamlCBindingWithSourceCompilation>
		
		<!-- Min OS Versions -->
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">31.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.19041.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">15.0</SupportedOSPlatformVersion>
	</PropertyGroup>

	<!-- iOS Spezifisch -->
	<PropertyGroup Condition="$(TargetFramework.Contains('-ios'))">
		<RuntimeIdentifier>ios-arm64</RuntimeIdentifier>
		<IncludeSwiftStandardLibraries>true</IncludeSwiftStandardLibraries>
	</PropertyGroup>

	<!-- Windows Spezifisch -->
	<PropertyGroup Condition="$(TargetFramework.Contains('-windows'))">
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>
		<WindowsPackageType>None</WindowsPackageType>
		<WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>
		<EnableWindowsTargeting>true</EnableWindowsTargeting>	
	</PropertyGroup>

	<!-- Android Signing (Release) -->
	<PropertyGroup Condition="'$(Configuration)' == 'Release' And $(TargetFramework.Contains('-android'))">
		<AndroidKeyStore>true</AndroidKeyStore>
		<AndroidSigningKeyAlias>$(AndroidKeyAlias)</AndroidSigningKeyAlias>
		<AndroidSigningKeyPass>$(AndroidKeyPassword)</AndroidSigningKeyPass>
		<AndroidSigningStorePass>$(AndroidStorePassword)</AndroidSigningStorePass>
		<AndroidSigningKeyStore>$(AndroidKeyStorePath)</AndroidSigningKeyStore>
	</PropertyGroup>

	<!-- Android Debug/Release Flags -->
	<PropertyGroup Condition="$(TargetFramework.Contains('-android'))">
		<AndroidPackageFormat>aab</AndroidPackageFormat>
		<AndroidUseAapt2>True</AndroidUseAapt2>
		<AndroidCreatePackagePerAbi>False</AndroidCreatePackagePerAbi>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)' == 'Release' And $(TargetFramework.Contains('-android'))">
		<AndroidLinkTool>r8</AndroidLinkTool>
		<RunAOTCompilation>true</RunAOTCompilation>
		<AndroidGenerateDebugSymbols>true</AndroidGenerateDebugSymbols>
		<AndroidStripNativeDebugSymbols>false</AndroidStripNativeDebugSymbols>
		<AndroidEnableProfiledAot>true</AndroidEnableProfiledAot>
	</PropertyGroup>

	<!-- General Release Flags -->
	<PropertyGroup Condition="'$(Configuration)'=='Release'">
		<UseHotReload>false</UseHotReload>
		<DebugSymbols>false</DebugSymbols>
		<Optimize>true</Optimize>
	</PropertyGroup>

	<PropertyGroup>
		<ApplicationIconScaling>true</ApplicationIconScaling>
		<PackageIcon>appicon.png</PackageIcon>
		<UserSecretsId>26b2a0b7-a7b6-4a99-8b47-0e34092c765d</UserSecretsId>
		<WindowsPackageType>None</WindowsPackageType>
	</PropertyGroup>

	<ItemGroup>
		<!-- Android mit Hintergrundfarbe -->
		<MauiIcon Include="Resources\AppIcon\appicon.svg" ForegroundFile="Resources\AppIcon\appiconfg.svg" ForegroundScale="0.65" Condition="$(TargetFramework.Contains('-android'))" />
		<!-- iOS mit eigenem, flachem Icon -->
		<MauiIcon Include="Resources\AppIcon\appiconfg.svg" Color="#ffffff" Link="appicon" Condition="$(TargetFramework.Contains('-ios'))" />
		<!-- Windows transparent -->
		<MauiIcon Include="Resources\AppIcon\appiconfg.svg" Condition="$(TargetFramework.Contains('-windows'))" />
		<!-- Splash Screen -->
		<MauiSplashScreen Include="Resources\Splash\splash.svg" Color="#ffffff" BaseSize="160,160" />
		<!-- Images & Fonts -->
		<MauiImage Include="Resources\Images\*" />
		<MauiFont Include="Resources\Fonts\*" />
		<MauiAsset Include="Resources\Raw\**" Exclude="Resources\Raw\editor.html" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="Resources\Raw\editor.html" />
	</ItemGroup>

    <ItemGroup Condition="$(TargetFramework.Contains('-windows'))">
        <PackageReference Include="Microsoft.WindowsAppSDK" Version="2.3.1" />
        <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.28000.2526" />
    </ItemGroup>

	<ItemGroup>
		<PackageReference Include="CameraMaui" Version="1.4.14" />
		<PackageReference Include="Codeuctivity.OpenXmlPowerTools" Version="10.0.579" />
		<PackageReference Include="CommunityToolkit.Maui" Version="15.0.0" />
		<PackageReference Include="CommunityToolkit.Maui.Core" Version="15.0.0" />
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
		<PackageReference Include="DocumentFormat.OpenXml" Version="3.5.1" />
		<PackageReference Include="FFImageLoading.Maui" Version="1.3.2" />
		<PackageReference Include="Mapsui" Version="5.1.0" />
		<PackageReference Include="Mapsui.Maui" Version="5.1.0" />
		<PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="10.0.10" />
		<PackageReference Include="Microsoft.Maui.Controls" Version="10.0.90" />
		<PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="10.0.90" />
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="10.0.10" />
		<PackageReference Include="Sentry.Maui" Version="6.8.0" />
		<PackageReference Include="SharpKml.Core" Version="6.1.0" />
		<PackageReference Include="SkiaSharp.Views.Maui.Controls" Version="4.152.0-preview.1.1" />
	</ItemGroup>

	<ItemGroup>
		<None Update="Resources\AppIcon\appicon.png">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Controls\BorderedEditor.xaml.cs">
		  <DependentUpon>BorderedEditor.xaml</DependentUpon>
		</Compile>
		<Compile Update="Controls\RangeSlider.xaml.cs">
			<DependentUpon>RangeSlider.xaml</DependentUpon>
		</Compile>
		<Compile Update="Resources\Languages\AppResources.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>AppResources.resx</DependentUpon>
		</Compile>
		<Compile Update="Views\FotoGallery.xaml.cs">
			<DependentUpon>FotoGallery.xaml</DependentUpon>
		</Compile>
		<Compile Update="Views\MapView.xaml.cs">
			<DependentUpon>MapView.xaml</DependentUpon>
		</Compile>
		<Compile Update="Views\NewPage.xaml.cs">
		  <DependentUpon>NewPage.xaml</DependentUpon>
		</Compile>
		<Compile Update="Views\PopupCalendarView.xaml.cs">
			<DependentUpon>PopupCalendarView.xaml</DependentUpon>
		</Compile>
		<Compile Update="Views\PopupShapeSelect.xaml.cs">
			<DependentUpon>PopupShapeSelect.xaml</DependentUpon>
		</Compile>
		<Compile Update="Views\PopupTextEdit.xaml.cs">
			<DependentUpon>PopupTextEdit.xaml</DependentUpon>
		</Compile>
		<Compile Update="Views\PopupStyleEditor.xaml.cs">
			<DependentUpon>PopupStyleEditor.xaml</DependentUpon>
		</Compile>
		<Compile Update="Views\PopupPinView.xaml.cs">
			<DependentUpon>PopupPinView.xaml</DependentUpon>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Update="Resources\Languages\AppResources.de.resx">
			<SubType>Designer</SubType>
		</EmbeddedResource>
		<EmbeddedResource Update="Resources\Languages\AppResources.resx">
			<Generator>ResXFileCodeGenerator</Generator>
			<LastGenOutput>AppResources.Designer.cs</LastGenOutput>
		</EmbeddedResource>
		<EmbeddedResource Update="Resources\Languages\AppResources.en.resx" />
	</ItemGroup>

	<ItemGroup>
		<MauiXaml Update="Controls\BorderedEditor.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Controls\BorderedEntry.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Controls\BorderedExpander.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Controls\CalendarView.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Resources\Styles\RadioButtonStyles.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Controls\RangeSlider.xaml" Generator="MSBuild:Compile" />
		<MauiXaml Update="Controls\CustomRadioPicker.xaml" Generator="MSBuild:Compile" />
		<MauiXaml Update="Views\CameraView.xaml" Generator="MSBuild:Compile" />
		<MauiXaml Update="Views\FotoGallery.xaml" Generator="MSBuild:Compile" />
		<MauiXaml Update="Views\MapView.xaml" Generator="MSBuild:Compile" />
		<MauiXaml Update="Views\NewPage.xaml" Generator="MSBuild:Compile" />
		<MauiXaml Update="Views\PopupCalendarView.xaml" Generator="MSBuild:Compile" />
		<MauiXaml Update="Views\PopupRadioPicker.xaml" Generator="MSBuild:Compile" />
		<MauiXaml Update="Views\PopupShapeSelect.xaml" Generator="MSBuild:Compile" />
		<MauiXaml Update="Views\PopupTextEdit.xaml" Generator="MSBuild:Compile" />
		<MauiXaml Update="Views\PopupStyleEditor.xaml" Generator="MSBuild:Compile" />
		<MauiXaml Update="Views\PopupPinView.xaml" Generator="MSBuild:Compile" />
	</ItemGroup>

	<PropertyGroup Condition="$(TargetFramework.Contains('-ios'))">
		<SentryUploadSymbols>true</SentryUploadSymbols>
		<SentryOrg>fankman-dev</SentryOrg>
		<SentryProject>snapdoc_maui</SentryProject>
		<SentryAuthToken>$(SENTRY_AUTH_TOKEN)</SentryAuthToken>
		<SentryUploadPdb>true</SentryUploadPdb>
	</PropertyGroup>
</Project>
