name: Build MAUI iOS

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # Das erlaubt dir, den Build manuell unter "Actions" zu starten

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Install MAUI Workloads
        run: |
          dotnet workload install maui-ios
          dotnet workload restore

      - name: Decode Signing Files
        run: |
          echo "${{ secrets.IOS_CERTIFICATE_BASE64 }}" | base64 --decode > certificate.p12
          echo "${{ secrets.IOS_PROVISION_BASE64 }}" | base64 --decode > profile.mobileprovision

      - name: Select Xcode Version
        run: |
          sudo xcode-select -s /Applications/Xcode_26.2.app || sudo xcode-select -s /Applications/Xcode.app
          xcodebuild -version
          
      - name: Build and Sign IPA
        run: |
          dotnet publish SnapDoc/SnapDoc.csproj -f net10.0-ios -c Release \
          -p:ArchiveOnBuild=true \
          -p:CodesignKey="Apple Distribution" \
          -p:CodesignProvision="MAUI_AppStore_Distribution" \
          -p:RuntimeIdentifier=ios-arm64 \
          -p:CheckEolTargetFramework=false \
          -p:MtouchNoWarn=7091 \
          -p:SuppressXCodeVersionMismatch=true
